<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Generated by GameMaker:Studio http://www.yoyogames.com/gamemaker/studio -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="pragma" content="no-cache"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name ="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta charset="utf-8"/>

        <!-- Set the title bar of the page -->
        <title>Mente Criativa</title>
        <!--link externos-->
        <?php require_once $_SERVER['DOCUMENT_ROOT'].'/projetoFinal/includes/linksExternos.php'; ?>
        <!-- css default -->
        <link rel="stylesheet" href="/projetoFinal/css/cssJogo.css">
    </head>

    <body>
        <div class="container-fluid col-12 col-xl-10">
            <!--cabeçalho-->
            <?php require_once $_SERVER['DOCUMENT_ROOT'].'/projetoFinal/includes/header.php'; ?>

            <div class="gm4html5_div_class" id="gm4html5_div_id">
                <!-- Create the canvas element the game draws to -->
                <div class="container-fluid jogo">
                    <canvas id="canvas" width="992" height="768">
                       <p>Your browser doesn't support HTML5 canvas.</p>
                    </canvas>
                </div>
            </div>